### ISSUE TITLE
'plasma5-applets-0-toggle' package from netrunner repo is missing required modules

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#11]
'python-msgpack' and 'python-gevent' packages should be added as dependencies for this package to work properly.

Also 'zeronet' package could be added into netrunner repo, added as a dependency for this applet and configured to work with it out of the box.

Manual installation of Python packages by clicking link in applet's error message didn't work for me, though zeronet can be installed manually from it.

![zeronet-missing-python-packages](https://user-images.githubusercontent.com/2657014/29353790-11ba9b40-8274-11e7-9c58-7701b2f0fd28.png)

**Comment by NuLogicSystems** [comment]
I'll add those two dependencies to the PKGBUILD now. However, I will not be able to pull the changes and rebuild the package till I get back on Friday or Saturday..

**Comment by NuLogicSystems** [comment]
Updated for these two dependencies.

**Comment by NuLogicSystems** [comment]
The zeronet portion of this issue is a sugestion not a bug, this should be under QA-Sugestions and not here.
