### ISSUE TITLE
'plymouth-theme-netrunner-classic', 'artwork-netrunner-icons' and 'artwork-grub-theme-netrunner-black' packages have incorrect package descriptions

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#12]
'Default Sounds for Netrunner Rolling' - possibly duplicate descriptions of 'artwork-netrunner-sounds' package.

**Comment by NuLogicSystems** [comment]
Manjaro no longer supports plymouth, arch never really did.
But it is possible that the description fields were overlooked at the time of creating these packages, and a simple fix.

**Comment by NuLogicSystems** [comment]
Descriptions should now be fixed in the updated packages.
