### ISSUE TITLE
'opendht' package in netrunner repo is outdated comparing to 'opendht' package from community repo

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#14]
netrunner/opendht 1:1.3.0.r20.gb08b2f1-1
community/opendht 1:1.3.5-1

**Comment by notuxius** [comment]
Also same versions - but outdated package release for 'kashmir' package between netrunner and community repos.

**Comment by NuLogicSystems** [comment]
Some of these packages were not available via the community repo at the time we made them.
I'll take a look to see what else has been added, removed or updated when I gat back.
