### ISSUE TITLE
'restbed-latest' package in netrunner repo is outdated and replaced by community's 'restbed' package

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#15]
'restbed' package is replacing 'restbed-latest' upon update - because 'restbed' is conflicting with 'restbed-latest'.

**Comment by NuLogicSystems** [comment]
Yes because restbed was added to the Manjaro repository after our packages were made, and after the ISO was released.
This is related these:
https://github.com/netrunner-rolling/QA/issues/10
https://github.com/netrunner-rolling/QA/issues/14
