### ISSUE TITLE
Firefox-KDE and Thunderbird-KDE do not start after updates

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#17]
Firefox-KDE and Thunderbird-KDE were tested in Manjaro KDE 17.0.6 Stable after updates - Firefox starts ok, Thunderbird not starts with next error:
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libicui18n.so.59: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

In Netrunner Rolling - both Firefox-KDE and Thunderbird-KDE do not start with same error after updates.

Possible solution would be - to use binary package from torvic9 https://github.com/torvic9/firefox-kde repo in our one

**Comment by NuLogicSystems** [comment]
This was already discussed and was determined to drop the suse patched versions.
Both Firefox 57.0 and Thunderbird 52.5.0 are working fine on my Netrunner Rolling systems.

I did update the plugins we ship to their webextension version.
However the add-to-searchbar extension has had no such update so it will no longer load, but this will not cause the crash you experienced. 

Did you add any 3rd party plugins or extensions that have not been updated to webextension?

Are you using freshplayerplugin + pepperflash? 
These are known to cause instability and crashes under Firefox 57.
Also, many of the flash functions will no longer work with these under FF57, most flash based games will no longer be able to download game data, etc.
Flashplugin is the only option at the moment for a stable and functioning FF+Flash experience.

**Comment by notuxius** [comment]
My steps:
1. I installed and updated the distribution.
2. Not added/removed any Firefox/Thunderbird extensions.
3. Launched Firefox/Thunderbird and got above mentioned error.

New Netrunner users most likely will get the same error after downloading current iso and doing these steps.

Searched in Octopi for 'firefox' and 'thunderbird' and found out that KDE versions are displayed as foreign packages and they weren't replaced by regular versions after updates.

**Comment by NuLogicSystems** [comment]
I have 4 machines here running Netrunner Rolling and none of them crashed, one I installed just yesterday. May I ask what ISO your referring to as there has only been one released this year 2017.07?

**Comment by notuxius** [comment]
Yes, the latest 2017.07 released iso

**Comment by NuLogicSystems** [comment]
Did you use octopi for the update?
It should have asked you to use a terminal for the update since user intervention is required, you would have to hit Y.
Also it should have updated manjaro-system and keys first, then restarted the update with the rest of the updates listed. AKA it should have been a two step process at minimum.

**Comment by NuLogicSystems** [comment]
PS, I'm already working on a new ISO.

BTW, make sure your not running freshplayerplugin, it's very unstable and in a incomplete state atm, as I mentioned already. It was actually crashing FF on the new iso's live system. It's not playing nice with other extensions and causing crashes. Also Facebook games like bejeweled blitz can't access scores, etc. just get a warning that it couldn't communicate, or something along those lines. Normal flashplugin works properly however.

**Comment by notuxius** [comment]
Reinstalled in VirtualBox - updated all packages in Octopi terminal -
this included updating of Arch/Manjaro keyrings and Manjaro System package and replacing some packages in Octopi terminal.

Here is screenshot right after the system reboot - trying to launch FF and Thunderbird:
![virtualbox_netrunner linux_12_12_2017_18_36_20](https://user-images.githubusercontent.com/2657014/33896706-31c39a5e-df6c-11e7-8e99-8ffa32a6b3c1.png)

**Comment by NuLogicSystems** [comment]
Check if xulruner is installed it shouldn't be.
sudo pacman -S icu
I'll need to investigate why this is happening to you.

The icu package should always be installed as it's a dependency of boost-libs, as well as harfbuzz-icu kdelibs lib32-icu libcdr libfbclient libmspub libvisio libxml2 manjaro-settings-manager qt5-base raptor thunderbird.

I'll check this again tonight, but octopi should have said these packages were in conflict and asked to remove the kde versions.

In the meantime, could you please check your mirror: http://repo.manjaro.org/

**Comment by notuxius** [comment]
switched to Canada server with same results

'icu' 'lib32-icu' are installed at versions 60.1-1
'firefox-kde' is at version 54.0.1-1
'thunderbird' 52.2.1-1

**Comment by NuLogicSystems** [comment]
Well at any rate, firefox-kde is no longer supported switch it out.
The extensions in our repositories have already been updated to their latestfor webextension versions.
Octopi should have asked you :: firefox and firefox-kde are in conflict. Remove firefox-kde? [y/N] after asking to use a terminal. I will look into the issue further this evening.

**Comment by NuLogicSystems** [comment]
Octopi can be funny beast though.
On one of my systems, while it did ask that question, it was still listing firefox-kde as version 57.0-1 from the AUR, which is itself a bit strange since that version was never in the repositories or in the AUR.

**Comment by NuLogicSystems** [comment]
I now see what happened, upstream manjaro stoped compiling these themselves and are now just repackaging the upstream packages from arch. However, they forgot to add in some conflicts and provides lines or even a replaces line. I will try and contact Philip from manjaro to correct this, I'm sure it will be effecting them as well.

**Comment by NuLogicSystems** [comment]
Done, lets see if I get a response:
https://github.com/manjaro/packages-extra/commit/f7322a450c992f82c2314441d4a4f894ed25670c#commitcomment-26228179

**Comment by NuLogicSystems** [comment]
If I don't get a response by tomorrow, and/or nothing is going to get done by upstream Manjaro, I'll make a transitional package for our repository. But for now, It's time for bed.

**Comment by NuLogicSystems** [comment]
Looks like upstream Manjaro may add in the replaces lines required to switch out the kde patched versions, for the normal non-patched versions. I'll keep you updated.
