### ISSUE TITLE
Firefox 58.0.1 failure in cck2.

### ISSUE THREAD

**Issue by NuLogicSystems** [netrunner-rolling/QA-Bugs#18]
Firefox 58 doesn't like our cck2, I'm now getting this error:
![screenshot_20180201_130047](https://user-images.githubusercontent.com/10186587/35694796-7895231a-0750-11e8-9bcb-15b7dfeb425d.png)

I don't know enough about cck2 to fix this.

**Comment by star-buck** [comment]
Whats cck2 again for?
Is it already breaking for installed systems?
Any solution to autofix without the users doing something fancy?

**Comment by NuLogicSystems** [comment]
It's pulled from netrunner-common, and how shadeslayer and leszek customized firefox.
I've been trying to follow it, but it's a lot of java scripting:
https://mike.kaply.com/cck2/
https://github.com/netrunner-common/netrunner-settings-firefox
https://github.com/netrunner-rolling/netrunner-settings-firefox

**Comment by star-buck** [comment]
Then please make this common and ask for help.

**Comment by NuLogicSystems** [comment]
Will do.

**Comment by NuLogicSystems** [comment]
cck2 needed to be updated for FF58, update pushed to repository.
