### ISSUE TITLE
Unable to start KInfocenter with "Couldn't find current GLX or EGL context." error 

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#19]
Also both "About System" and "About System Extended" are affected

**Comment by NuLogicSystems** [comment]
Next time, please post the actual error from the console:
```
$ kcmshell5 about-distro
kcmshell5: Couldn't find current GLX or EGL context.
```
This looks like an upstream bug, issue.
What display chip and drivers are you using?
Example: Intel - opensource - xorg - mesa
Can you post the output of glxinfo?

**Comment by notuxius** [comment]
I'm using stack that you specified on Intel 4400 - i tried to reproduce this error in VirtualBox in Manjaro KDE and in Netrunner Rolling - Manjaro KDE has no such error - Netrunner Rolling has such error also on VM drivers

**Comment by NuLogicSystems** [comment]
OK, i found the issue, It is indeed our about_extended package causing the issue. 
However, I'm having issues recompiling this ATM. 
You can either wait for me to work past these compile errors i'm getting and update the package, or remove about_extended for now.

**Comment by notuxius** [comment]
After removing of kcm-about-extended package - KInfocenter starts ok - 'About System' section in it shows 'The shared library was not found.' error

output in console:

```
$ kcmshell5 about-distro
org.kde.kcoreaddons: Error loading plugin "kcm_about_extended" "The shared library was not found." 
Plugin search paths are ("/usr/lib/qt/plugins", "/usr/bin") 
The environment variable QT_PLUGIN_PATH might be not correctly set
Error loading plugin: "The shared library was not found."
```

**Comment by NuLogicSystems** [comment]
Yes this, this is due to our systemsettings diversion.
Once I have about-extended compiled you can reinstall it.
You could temporarily remove /usr/share/default-settings/plasma5-profile/kservices5/about-distro.desktop until I have this fixed if you like. 
This file (diversion) was added to remove the double entry in kinfocenter and to ensure consitancy.

**Comment by NuLogicSystems** [comment]
I think I found the root cause of both the error and my inability to compile.
solid in Manjaro is at 5.43 in both stable and in testing branch, all the rest of frameworks is at 5.44.
The manjaro unstable branch has the corect version of all kf5.

**Comment by NuLogicSystems** [comment]
Nope, that wasn't it.
Updateing solid allowed me to get about-extrended compiled, but it still crashes with the same error.

@star-buck,
We will need someone to look at the about-extended source code.

@notuxius,
Can you please post this issue upstream over at the ds9-extras, about-extended github tracker?

**Comment by notuxius** [comment]
Here is the issue in upstream https://github.com/ds9-extras/kcm-about-extended/issues/4

**Comment by NuLogicSystems** [comment]
This could also just be the Intel kernel driver or a mesa issue.
I only have Intel machines so I can't test other drivers.
However, when I have time later this evening, I'll try a downgrading the intel and mesa drivers, as well as try diferent kernels.

**Comment by NuLogicSystems** [comment]
@notuxius,
Thanks, hopefully someone can fix the code.
In the meantime, I do still plan on looking at downgrading the mesa drivers, etc. to see if that helps.

**Comment by NuLogicSystems** [comment]
No luck, I tried every version of mesa available via downgrade.

**Comment by NuLogicSystems** [comment]
I think I found the issue:
[https://github.com/anholt/libepoxy/issues/160 ](https://github.com/anholt/libepoxy/issues/160)
Upstream kcm-about-distro (kinfocenter) doesn't use epoxy.
Downgrading libepoxy from 1.5.0 to 1.4.3 fixes the issue:
`sudo pacman -S downgrade`
`sudo downgrade libepoxy`
Select 1.4.3 from list and follow the prompts.
When prompted to add libepoxy to the ignore list select y (atleast until this bug gets fixed).

**Comment by NuLogicSystems** [comment]
Upstream bug..

**Comment by NuLogicSystems** [comment]
If downgrade doesn't want to work:
sudo pacman -U https://archive.archlinux.org/packages/l/libepoxy/libepoxy-1.4.3-1-x86_64.pkg.tar.xz

**Comment by NuLogicSystems** [comment]
The Manjaro package libepoxy  1.5.1+6+gb80ea6a-1 fixes this issue.
Work around no longer needed.
